# 文本分析配置文件
analysis:
  # 评论采样大小（用于性能优化）
  comment_sample_size: 5000
  
  # 关键词提取数量
  top_keywords: 20
  
  # 情感分析阈值
  positive_threshold: 0.6
  negative_threshold: 0.4
  
  # 词云配置
  wordcloud:
    width: 800
    height: 400
    max_words: 100
    background_color: "white"
    colormap: "viridis"

visualization:
  # 图表样式
  figure_size: [15, 12]
  dpi: 100
  
  # 字体设置
  font_family: "SimHei"
  
output:
  # 输出目录
  results_dir: "results"
  
  # 图片格式
  image_format: "png"
  
  # 保存分析结果
  save_results: true
